dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtdeclarative5-dev xvfb

script:
  - mkdir build && cd build
  - cmake ..
  - make
