dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install build-essential qtbase5-dev qtdeclarative5-dev
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - mkdir build && cd build
  - cmake ..
  - make
