language: cpp
compiler: gcc
sudo: require
dist: trusty

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq
    
install: 
  - sudo apt-get -y install qt59base qt59declarative
  - . /opt/qt*/bin/qt*-env.sh || true

script:
  - mkdir build && cd build
  - cmake ..
  - make
